stages:
- name: go-test
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: "mkdir -p /go/src/github.com/golang\n\nln -s $(pwd) /go/src/github.com/golang/example
        \ncd  /go/src/github.com/golang/example\ngo test"
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v1
      pushRemote: true
      registry: 127.0.0.1:34593
timeout: 60
